### ISSUE TITLE
Meeting request - to educate and discuss about GSuite Options

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Infrastructure#7]
Creating a policy and orientation packet for the use of GSuties has been on the table for a while for RDG Board.  We now have the capacity to take it off the table and create it.   

We have one pressing need which is to create documents for our minutes that are sharable with the public.  The System is not giving that to us as an option right now. Our secretary is working very hard to create PDFs.  In addition to the level of work, the PDFs are not complete, only showing the first page. Our goal is to have sharable docs by the first week of January so that we can share our agenda and minutes. Our other goal is to create an onboarding document for new board members by the meeting in February 2021. 

I have made a few previous attempts to get something drafted; once to ask someone else and once where I gave it a try.  Neither quite worked out.  Perhaps a committee effort will help us to get this started.  

Lacey, Dirk, and Sean, would you be able to meet on this topic to see if we can generate a draft of our policies and procedures when it comes to 

Thanks for all of your assistance, 

Kris

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma I'm in.

Would folks be open to the idea of keeping minutes right on `recoverydharma.org`?

PDFs are not as user-friendly: they may require a software add-on (Acrobat Reader), the are heavier weight (in terms of data payload) and that affects mobile browsing (data limits, download speed, rendering speed, power consumption), and they present differing controls depending on the user agent (context menu changes in some browser for PDFs and so forth).

Since the minutes ultimately get published to the website and that's where folks would go (or at least I would go) to find the latest goings-on, why not write the minutes directly on `recoverydharam.org`?

At the start of each Board meeting:

1. Secretary logs onto `recoverydharma.org` and creates a new `Post`.
2. As the meeting transpires, the secretary types out everything that happens in the `Post`.
3. When the meeting is done, secretary clicks `Save`.

It's the same workflow as you do already, just in WordPress instead of Google Docs. You even have the same controls: bold, italic, underline, bullet list, numeric list, etc. They even use the same icons so the learning curve is minimal.

When the board _approves_ the minutes, the secretary can go back to the `Post` and click `Publish`. Now the minutes are live for everyone.

**Comment by KrisRecoveryDharma** [comment]
Ah! So they aren't published at first.  Secretaries are rarely able to
leave the minutes at the end of the meeting. There are usually edits and
clarification to be made. They can log back in to make those corrections,
right?

We use a table format.  Could we continue to use that?

Thank you! I love it!

**Comment by KrisRecoveryDharma** [comment]
We have quite a few attachments to to the minutes.  They are also in PDF
format.  Any thoughts on how to manage these?

**Comment by nutjob4life** [comment]
@KrisRecoveryDharma yes, the secretary can go back and edit a `Post` object to their heart's content for days or weeks afterward before finally hitting `Publish`. Attachments could be uploaded to the WordPress media library and linked to the `Post`.

**Comment by KrisRecoveryDharma** [comment]
Thank you! 
Our time together was extremely helpful!
Kris
